### ISSUE TITLE
Please release the results

### ISSUE THREAD

**Issue by xinshuoweng** [tobiasfshr/MOTSFusion#1]
Hi,

Thanks for your wonderful work. Could you please release the 3D tracking and reconstruction results produced by your model?

**Comment by tobiasfshr** [comment]
Hi, 

Sorry for the late reply. I just updated the README file to include tracking results on MOTS test set as well as detections and segmentations for all setups. Hope that helps.

Best regards,
Tobias

**Comment by xinshuoweng** [comment]
Thanks for the feedback! I appreciate it.

The result files on the KITTI test set seems to have an incorrect character encoding, which cannot be recognized by the plain text reader. For example, in the result files, I have got something like "001N10gm20YRM0l^10TaN1".

In addition to the KITTI test results, could you also provide your results on the validation set?

Thanks!

**Comment by likojack** [comment]
Hi Xinshuo and Tobias,

Did you manage to extract the results at the end?

I tried to run the pipeline on the validation set but failed to replicate the performance. It would be great if the results on val set could be made public.
